name: publish to gh pages

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: npm i
    - run: npm ci
    - run: npm run build
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git --work-tree build add --all
    - run: git commit -m "Automatic Build and Deploy run by GitHub Actions"
    - run: git push origin HEAD:gh-pages --force
    
